### ISSUE TITLE
[Question] Why not take type's arguments in a separate column?

### ISSUE THREAD

**Issue by Adrien-ANTON-LUDWIG** [XLSForm/xlsform.github.io#239]
Hello :wave: 

First of all, thanks for this standard! 🚀 I like standards. 😄

This is not an issue but rather a question. I'm simply curious.

Looking at [short list of types](https://xlsform.org/en/#question-types) while writing an XLSForm parser, an question came to me.
There are very few types taking arguments : `select` derivatives and `rank`. Even counting each `select`,  that's only 20% of the main types shown on the page above, and much less for the complete list.
But taking arguments this way, i.e. after the type in the same column, makes it necessary to check for these types and treat them differently to parse the arguments.

To me, a seperate optional column accepting arguments seems simpler. For example, the `select_one`, `select_multiple` and `rank` types could take there arguments in the `choices` column (or a better name to avoid confusion with the choices sheet). That way, the types can easily be compared to there exact string and the parsing is replaced by simpy reading the content of the other column. Even for writing the form in a spreadsheet, I feel it's clearer (more visual) to separate the type from the argument.

What motivated the first implementation rather than the second?

Thanks for your time! :wink:

**Comment by lognaturel** [comment]
I wasn't there when these decisions were originally made so I can't speak to the original motivation. 

What I can say as someone who authors forms is that in my head the type is "select one from xyz" where xyz is the choice source. It's convenient that the `type` in XLSForm matches that. Another consideration is form width. One of the beautiful things about XLSForm is that it's both vertically and horizontally compact: you can see a lot of context about a form in one screen. I often set the type column to a size at which most selects will have their type on the next line. I sacrifice a little bit of vertical compactness to guarantee more fits on my screen horizontally. A separate column would make that harder. Another nice property of this choice is that all forms can start with the three required columns `type`, `name`, `label`. Having a very sparsely populated column in between type and name would decrease scan-ability.

> makes it necessary to check for these types and treat them differently to parse the arguments.

What's your concern around that? Performance? Code cleanliness? If it's performance, keep in mind that XLSForms are typically in the 200-400 row range. I've seen as big as 10k. The performance hit is absolutely minimal. If it's code cleanliness, you should be able to wrap that all up in a nice abstraction and never look at it again.

If at all possible, consider contributing to `https://github.com/xlsform/pyxform` rather than rolling your own! You might also be interested in https://github.com/getodk/pyxform-http

**Comment by Adrien-LUDWIG** [comment]
Thank you for your reply!

I understand your arguments. Even if they are not undeniable advantages, they may have weighed in the balance for this entirely subjective implementation.

My concern (if you can call it that, it's rather too much curiosity) was more about the "elegance of the standard", if that makes sense.

I've already had a look at `pyxform` but I can't see how to relate to it. I'm trying to convert XLSForms into QGIS forms (layers with the given fields). If I'm not mistaken, `pyxform` is mainly focused on converting to XForms ODK. Is there an intermediate step where I could plug in to output a QGIS form without having to parse the XLSForm myself (to benefit from all the checks that `pyxform` already implements)?

**Comment by lognaturel** [comment]
> about the "elegance of the standard"

Yes, that makes sense! If you're interested in being involved in the evolution of the standard, a lot of that happens on [the ODK forum](https://forum.getodk.org/) these days. You're welcome to join in.

> Is there an intermediate step where I could plug in to output a QGIS form without having to parse the XLSForm myself

Yes! Take a look at [`xls2json`](https://github.com/XLSForm/pyxform/blob/master/pyxform/xls2json.py) which provides an intermediary json representation. You can then see [`xls2xform`](https://github.com/XLSForm/pyxform/blob/master/pyxform/xls2xform.py) for how it uses the JSON representation to go to XForm. You could similarly build a script that depends on `xls2json` and then goes to another format.

**Comment by Adrien-LUDWIG** [comment]
Sorry for the late reply.

Thanks so much for the suggestions! It's exactly what I was looking for. Unfortunately, I won't be working on this project again, but I've made a good note of it for whoever takes it over. 

Thanks again for your time and help! 🎉
