### ISSUE TITLE
Survey123 Connect functionality issue

### ISSUE THREAD

**Issue by KirstyNZ** [XLSForm/xlsform.github.io#59]
Hi, 
When I open Survey123Connect and open a Survey, there are issues with the display. Some letters display, others don't, lots of words are missing and if I click around, things appear and disappear randomly. 
I have spoken with Esri support and they have said it looks like a functionality issue that requires fixing. Screenshots attached. 

Thanks
![screen shot 2015-09-22 at 2 13 23 pm](https://cloud.githubusercontent.com/assets/14324326/10009689/e5c74680-6134-11e5-881b-6188bb21fe25.png)
![screen shot 2015-09-22 at 2 13 41 pm](https://cloud.githubusercontent.com/assets/14324326/10009690/e5cb630a-6134-11e5-8302-62eb65d03855.png)

**Comment by MartijnR** [comment]
If you have access to the XLSForm, and if when uploading to http://opendatakit.org/xiframe, you see that the output has missing characters, please file a bug here: https://github.com/XLSForm/pyxform/issues.

Otherwise, this is something internal to Survey123 that is not going to be addressed by anybody managing this repo.
